language: objective-c
xcode_workspace: PrimusEmitter.xcworkspace
xcode_scheme: PrimusEmitter
before_install:
  - gem install cocoapods
before_script:
  - brew update
  - brew upgrade xctool
notifications:
  slack: seegno:AoXFWrkPDMfOuaxvckPs7hc0
